name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy_api_docs:
    runs-on: ubuntu-24.04
    name: Deploy API Docs
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Generate docs
        working-directory: ./
        run: gem install --no-document yard && yardoc
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api

  create_github_release:
    runs-on: ubuntu-24.04
    name: Create GitHub Release PR
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          changelog-path: CHANGELOG.md
          default-branch: main
          include-v-in-tag: true
          package-name: semantic_boolean
          release-type: ruby
          version-file: lib/semantic_boolean/version.rb
